accepted = [
    "Apache-2.0",
    "MIT",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Zlib",
    "0BSD",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "CC0-1.0",
    "MPL-2.0",
    "OpenSSL",
    "Apache-2.0 WITH LLVM-exception",
    "CDLA-Permissive-2.0",
]

[ring]
accepted = ["MIT", "ISC", "OpenSSL"]
